const express = require('express');
const router = express.Router();
const { createOtp,mailRegisterOtp } = require('../../controller/auth/userRegister');
const {login, logout}=require('../../controller/auth/userLogin');
const{resetPasswordOtp,verifyOtpAndResetPassword}=require('../../controller/auth/userResetPassword');
router.post('/create-otp', createOtp);
router.post('/mail-register-otp', mailRegisterOtp);
router.post('/login',login);
router.post('/logout', logout);
router.post('/reset-password-otp', resetPasswordOtp);
router.post('/verify-otp-and-reset-password', verifyOtpAndResetPassword);
module.exports= router;